/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AirbnbRouteImport } from './routes/airbnb'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as HouseHuntingRouteImport } from './routes/house-hunting'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AirbnbRoute = AirbnbRouteImport.update({
  id: '/airbnb',
  path: '/airbnb',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseHuntingRoute = HouseHuntingRouteImport.update({
  id: '/house-hunting',
  path: '/house-hunting',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airbnb': typeof AirbnbRoute
  '/commercial': typeof CommercialRoute
  '/house-hunting': typeof HouseHuntingRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airbnb': typeof AirbnbRoute
  '/commercial': typeof CommercialRoute
  '/house-hunting': typeof HouseHuntingRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airbnb': typeof AirbnbRoute
  '/commercial': typeof CommercialRoute
  '/house-hunting': typeof HouseHuntingRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/airbnb'
    | '/commercial'
    | '/house-hunting'
    | '/login'
    | '/rentals'
    | '/settings'
    | '/signup'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/airbnb'
    | '/commercial'
    | '/house-hunting'
    | '/login'
    | '/rentals'
    | '/settings'
    | '/signup'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/airbnb'
    | '/commercial'
    | '/house-hunting'
    | '/login'
    | '/rentals'
    | '/settings'
    | '/signup'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AirbnbRoute: typeof AirbnbRoute
  CommercialRoute: typeof CommercialRoute
  HouseHuntingRoute: typeof HouseHuntingRoute
  LoginRoute: typeof LoginRoute
  RentalsRoute: typeof RentalsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airbnb': {
      id: '/airbnb'
      path: '/airbnb'
      fullPath: '/airbnb'
      preLoaderRoute: typeof AirbnbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-hunting': {
      id: '/house-hunting'
      path: '/house-hunting'
      fullPath: '/house-hunting'
      preLoaderRoute: typeof HouseHuntingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AirbnbRoute: AirbnbRoute,
  CommercialRoute: CommercialRoute,
  HouseHuntingRoute: HouseHuntingRoute,
  LoginRoute: LoginRoute,
  RentalsRoute: RentalsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
